#' Bayesian Posterior Distribution of Tredoux Effective Size
#'
#' Fits a Dirichlet-Multinomial conjugate model to mock-witness choice counts
#' and returns the posterior distribution of the Tredoux effective size E'.
#'
#' @param lineup_table A table of lineup choice counts (one entry per position).
#' @param alpha Dirichlet concentration parameter(s). A scalar (applied to
#'   all k positions) or a length-k numeric vector. Typical choices:
#'   0.5 (Jeffreys prior, default), 1 (uniform over the simplex), 0.1
#'   (weakly informative). Smaller values allow the posterior to concentrate
#'   more sharply around the observed proportions.
#' @param S Number of posterior draws. Default 10000.
#' @param credible_mass Width of the equal-tailed credible interval.
#'   Default 0.95.
#' @param threshold Optional finite scalar. When supplied, the function
#'   also reports P(E' < threshold | data) and P(E' > threshold | data),
#'   enabling direct probability statements about whether the lineup is
#'   functioning below or above a fairness benchmark.
#'
#' @details
#'   Tredoux's effective size E' = 1/sum(p_i^2) is mathematically identical
#'   to the reciprocal of the Herfindahl-Hirschman concentration index
#'   (Herfindahl, 1950; Hirschman, 1945) and to the reciprocal of
#'   Simpson's (1949) concentration statistic lambda. The Bayesian approach
#'   estimates the latent choice-probability vector p rather than E' directly.
#'
#'   With mock-witness counts n = (n_1, ..., n_k) and a Dirichlet prior:
#'   \deqn{p \sim \mathrm{Dirichlet}(\alpha_1, \ldots, \alpha_k),}
#'   the posterior is conjugate:
#'   \deqn{p \mid n \sim \mathrm{Dirichlet}(n_1 + \alpha_1, \ldots, n_k + \alpha_k).}
#'   Each posterior draw of p is mapped to a draw of E' via E'(p) = 1/sum(p_i^2).
#'   The resulting posterior distribution of E' summarises uncertainty about
#'   effective lineup size given the observed choices.
#'
#'   Dirichlet samples are generated by normalising independent Gamma draws
#'   (base R only; no additional package dependencies).
#'
#'   For publication, a prior sensitivity analysis using at least
#'   alpha = 0.5, 1, and 0.1 is recommended. If the substantive conclusion
#'   changes across these priors, the mock-witness sample is likely too small
#'   to support a confident fairness conclusion.
#'
#' @return An object of class \code{"esize_T_bayes"} containing:
#'   \describe{
#'     \item{E_draws}{Numeric vector of S posterior draws of E'.}
#'     \item{posterior_mean}{Posterior mean of E'.}
#'     \item{posterior_median}{Posterior median of E'.}
#'     \item{credible_interval}{Named 2-vector (lower, upper) giving the
#'       equal-tailed credible interval.}
#'     \item{prior_alpha}{The alpha vector used.}
#'     \item{n}{Total number of mock-witness choices.}
#'     \item{k}{Number of lineup positions.}
#'     \item{S}{Number of posterior draws.}
#'     \item{credible_mass}{Credible interval width.}
#'     \item{threshold}{Threshold value supplied, or NULL.}
#'     \item{threshold_probs}{List with \code{P_below} and \code{P_above},
#'       or NULL when no threshold was supplied.}
#'   }
#'
#' @references
#'   Herfindahl, O. C. (1950). \emph{Concentration in the US steel industry}.
#'   Doctoral dissertation, Columbia University.
#'
#'   Hirschman, A. O. (1945). \emph{National power and the structure of
#'   foreign trade}. University of California Press.
#'
#'   Simpson, E. H. (1949). Measurement of diversity. \emph{Nature, 163}, 688.
#'
#'   Tredoux, C. G. (1998). Statistical inference on measures of lineup
#'   fairness. \emph{Law and Human Behavior, 22}(2), 217-237.
#'
#' @seealso \code{\link{esize_T}}, \code{\link{esize_T_ci_n}},
#'   \code{\link{esize_boot_dist}}, \code{\link{esize_T_bayes_compare}}
#'
#' @examples
#' counts <- c(18, 7, 5, 4, 3, 3)
#' lineup_table <- as.table(setNames(counts, 1:6))
#'
#' # Default Jeffreys prior
#' result <- esize_T_bayes(lineup_table)
#' print(result)
#'
#' # With a fairness threshold
#' result2 <- esize_T_bayes(lineup_table, threshold = 4)
#' print(result2)
#'
#' # Plot the posterior
#' \dontrun{plot(result)}
#'
#' @importFrom stats rgamma quantile median
#' @export
esize_T_bayes <- function(lineup_table,
                          alpha        = 0.5,
                          S            = 10000,
                          credible_mass = 0.95,
                          threshold    = NULL) {

  counts <- as.numeric(lineup_table)
  k <- length(counts)
  N <- sum(counts)

  if (k < 2)
    stop("lineup_table must have at least 2 positions.", call. = FALSE)
  if (N < 1)
    stop("lineup_table must have at least one observation.", call. = FALSE)
  if (any(counts < 0))
    stop("lineup_table cannot contain negative counts.", call. = FALSE)
  if (length(S) != 1 || !is.finite(S) || S < 1)
    stop("S must be a positive integer.", call. = FALSE)
  S <- as.integer(S)
  if (length(credible_mass) != 1 || credible_mass <= 0 || credible_mass >= 1)
    stop("credible_mass must be strictly between 0 and 1.", call. = FALSE)
  if (!is.null(threshold) && (length(threshold) != 1 || !is.finite(threshold)))
    stop("threshold must be a finite scalar.", call. = FALSE)

  if (length(alpha) == 1) {
    alpha_vec <- rep(as.numeric(alpha), k)
  } else if (length(alpha) == k) {
    alpha_vec <- as.numeric(alpha)
  } else {
    stop("alpha must be a scalar or a vector of length k.", call. = FALSE)
  }
  if (any(alpha_vec <= 0))
    stop("All alpha values must be positive.", call. = FALSE)

  # Posterior: p | n ~ Dirichlet(n + alpha). Sample via normalised Gamma draws.
  shape_vec <- counts + alpha_vec
  g <- matrix(
    rgamma(S * k, shape = rep(shape_vec, each = S), rate = 1),
    nrow = S, ncol = k
  )
  p_draws <- g / rowSums(g)
  E_draws  <- 1 / rowSums(p_draws^2)

  tail_prob <- (1 - credible_mass) / 2
  ci <- quantile(E_draws, probs = c(tail_prob, 1 - tail_prob))
  names(ci) <- c("lower", "upper")

  threshold_probs <- NULL
  if (!is.null(threshold)) {
    threshold_probs <- list(
      P_below = mean(E_draws < threshold),
      P_above = mean(E_draws > threshold)
    )
  }

  structure(
    list(
      E_draws           = E_draws,
      posterior_mean    = mean(E_draws),
      posterior_median  = median(E_draws),
      credible_interval = ci,
      prior_alpha       = alpha_vec,
      n                 = N,
      k                 = k,
      S                 = S,
      credible_mass     = credible_mass,
      threshold         = threshold,
      threshold_probs   = threshold_probs
    ),
    class = "esize_T_bayes"
  )
}

#' Print method for esize_T_bayes objects
#'
#' @param x An object of class \code{"esize_T_bayes"}.
#' @param ... Further arguments (unused).
#' @export
print.esize_T_bayes <- function(x, ...) {
  alpha_label <- if (length(unique(x$prior_alpha)) == 1) {
    sprintf("%.2f", x$prior_alpha[1])
  } else {
    "heterogeneous (see $prior_alpha)"
  }
  cat("Bayesian Posterior: Tredoux Effective Size (E')\n")
  cat("------------------------------------------------\n")
  cat(sprintf("  k (positions): %d    N (choices): %d    S (draws): %d\n",
              x$k, x$n, x$S))
  cat(sprintf("  Prior: Dirichlet(alpha = %s)\n", alpha_label))
  cat(sprintf("  Posterior mean:   %.3f\n", x$posterior_mean))
  cat(sprintf("  Posterior median: %.3f\n", x$posterior_median))
  cat(sprintf("  %.0f%% credible interval: [%.3f, %.3f]\n",
              x$credible_mass * 100,
              x$credible_interval["lower"],
              x$credible_interval["upper"]))
  if (!is.null(x$threshold_probs)) {
    cat(sprintf("  P(E' < %.2f | data): %.3f\n",
                x$threshold, x$threshold_probs$P_below))
    cat(sprintf("  P(E' > %.2f | data): %.3f\n",
                x$threshold, x$threshold_probs$P_above))
  }
  invisible(x)
}

#' Plot method for esize_T_bayes objects
#'
#' Plots the posterior distribution of Tredoux's E' as a histogram overlaid
#' with a kernel density estimate. Vertical lines mark the posterior median
#' and credible interval bounds.
#'
#' @param x An object of class \code{"esize_T_bayes"}.
#' @param ... Further arguments (unused).
#' @return A ggplot object.
#' @export
plot.esize_T_bayes <- function(x, ...) {
  df  <- data.frame(E_prime = x$E_draws)
  ci  <- x$credible_interval
  ttl <- sprintf(
    "Posterior distribution of E' (Tredoux)\n%.0f%% credible interval: [%.2f, %.2f]",
    x$credible_mass * 100, ci["lower"], ci["upper"]
  )
  ggplot2::ggplot(df, ggplot2::aes(x = E_prime)) +
    ggplot2::geom_histogram(
      ggplot2::aes(y = ggplot2::after_stat(density)),
      bins = 40, fill = "#72b7b2", alpha = 0.6
    ) +
    ggplot2::geom_density(color = "#1f2d3d", linewidth = 1) +
    ggplot2::geom_vline(
      xintercept = ci["lower"], linetype = "dashed", color = "#c0392b"
    ) +
    ggplot2::geom_vline(
      xintercept = ci["upper"], linetype = "dashed", color = "#c0392b"
    ) +
    ggplot2::geom_vline(
      xintercept = x$posterior_median, linetype = "solid", color = "#2c3e50"
    ) +
    ggplot2::labs(
      x     = "E' (Tredoux effective size)",
      y     = "Density",
      title = ttl
    ) +
    ggplot2::theme_minimal(base_size = 12)
}

# Declare ggplot2 aesthetic column names to suppress R CMD check NOTEs
utils::globalVariables(c("E_prime", "delta"))

# ── Comparison function ───────────────────────────────────────────────────────

#' Bayesian Comparison of Tredoux Effective Size Across Two Lineups
#'
#' Fits independent Dirichlet-Multinomial models to two lineup tables and
#' returns the posterior distribution of the difference in Tredoux E'.
#'
#' @param table_a A table of choice counts for lineup A.
#' @param table_b A table of choice counts for lineup B.
#' @param alpha Dirichlet concentration parameter(s). Applied to both lineups.
#'   A scalar or a length-k vector (both lineups must have the same k).
#'   Default 0.5 (Jeffreys).
#' @param S Number of posterior draws per lineup. Default 10000.
#' @param credible_mass Width of the equal-tailed credible interval for the
#'   difference. Default 0.95.
#'
#' @details
#'   Independent Dirichlet-Multinomial posteriors are fitted for each lineup.
#'   The posterior of Delta = E'_A - E'_B is obtained by subtracting
#'   corresponding draws. P(E'_A > E'_B | data) is reported directly.
#'
#'   When the two lineups have different nominal sizes (different k), alpha
#'   must be a scalar; it is expanded independently for each lineup.
#'
#' @return An object of class \code{"esize_T_bayes_compare"} containing:
#'   \describe{
#'     \item{delta}{Posterior draws of Delta = E'_A - E'_B.}
#'     \item{posterior_mean}{Posterior mean of Delta.}
#'     \item{posterior_median}{Posterior median of Delta.}
#'     \item{credible_interval}{Named 2-vector (lower, upper) for Delta.}
#'     \item{P_A_greater}{Posterior probability that E'_A > E'_B.}
#'     \item{P_B_greater}{Posterior probability that E'_B > E'_A.}
#'     \item{result_a}{The \code{esize_T_bayes} object for lineup A.}
#'     \item{result_b}{The \code{esize_T_bayes} object for lineup B.}
#'     \item{credible_mass}{Credible interval width.}
#'     \item{S}{Number of posterior draws.}
#'   }
#'
#' @references
#'   Tredoux, C. G. (1998). Statistical inference on measures of lineup
#'   fairness. \emph{Law and Human Behavior, 22}(2), 217-237.
#'
#' @seealso \code{\link{esize_T_bayes}}, \code{\link{compare_eff_sizes.boot}}
#'
#' @examples
#' counts_a <- c(20, 5, 5, 5, 5, 5)
#' counts_b <- c(10, 8, 8, 8, 8, 8)
#' tab_a <- as.table(setNames(counts_a, 1:6))
#' tab_b <- as.table(setNames(counts_b, 1:6))
#'
#' result <- esize_T_bayes_compare(tab_a, tab_b)
#' print(result)
#' \dontrun{plot(result)}
#'
#' @importFrom stats quantile median
#' @export
esize_T_bayes_compare <- function(table_a,
                                  table_b,
                                  alpha         = 0.5,
                                  S             = 10000,
                                  credible_mass = 0.95) {

  ka <- length(as.numeric(table_a))
  kb <- length(as.numeric(table_b))

  if (length(alpha) > 1 && ka != kb) {
    stop(
      "alpha may only be a vector when both lineups have the same number of positions.",
      call. = FALSE
    )
  }

  res_a <- esize_T_bayes(table_a, alpha = alpha, S = S,
                         credible_mass = credible_mass)
  res_b <- esize_T_bayes(table_b, alpha = alpha, S = S,
                         credible_mass = credible_mass)

  delta <- res_a$E_draws - res_b$E_draws

  tail_prob <- (1 - credible_mass) / 2
  ci_delta  <- quantile(delta, probs = c(tail_prob, 1 - tail_prob))
  names(ci_delta) <- c("lower", "upper")

  structure(
    list(
      delta             = delta,
      posterior_mean    = mean(delta),
      posterior_median  = median(delta),
      credible_interval = ci_delta,
      P_A_greater       = mean(delta > 0),
      P_B_greater       = mean(delta < 0),
      result_a          = res_a,
      result_b          = res_b,
      credible_mass     = credible_mass,
      S                 = S
    ),
    class = "esize_T_bayes_compare"
  )
}

#' Print method for esize_T_bayes_compare objects
#'
#' @param x An object of class \code{"esize_T_bayes_compare"}.
#' @param ... Further arguments (unused).
#' @export
print.esize_T_bayes_compare <- function(x, ...) {
  cat("Bayesian Comparison: Tredoux Effective Size (E'_A vs E'_B)\n")
  cat("-----------------------------------------------------------\n")
  cat(sprintf("  Lineup A: k = %d, N = %d   |   Lineup B: k = %d, N = %d\n",
              x$result_a$k, x$result_a$n, x$result_b$k, x$result_b$n))
  cat(sprintf("  S (draws): %d    Prior: Dirichlet(alpha = %.2f)\n",
              x$S,
              if (length(unique(x$result_a$prior_alpha)) == 1)
                x$result_a$prior_alpha[1] else NA_real_))
  cat(sprintf("  E'_A posterior median: %.3f\n", x$result_a$posterior_median))
  cat(sprintf("  E'_B posterior median: %.3f\n", x$result_b$posterior_median))
  cat(sprintf("  Delta (E'_A - E'_B) posterior mean:   %.3f\n",
              x$posterior_mean))
  cat(sprintf("  Delta posterior median:               %.3f\n",
              x$posterior_median))
  cat(sprintf("  %.0f%% credible interval for Delta: [%.3f, %.3f]\n",
              x$credible_mass * 100,
              x$credible_interval["lower"],
              x$credible_interval["upper"]))
  cat(sprintf("  P(E'_A > E'_B | data): %.3f\n", x$P_A_greater))
  cat(sprintf("  P(E'_B > E'_A | data): %.3f\n", x$P_B_greater))
  invisible(x)
}

#' Plot method for esize_T_bayes_compare objects
#'
#' Plots the posterior distribution of Delta = E'_A - E'_B as a histogram
#' with density overlay. A vertical line at zero and shaded probability mass
#' above/below zero are shown.
#'
#' @param x An object of class \code{"esize_T_bayes_compare"}.
#' @param ... Further arguments (unused).
#' @return A ggplot object.
#' @export
plot.esize_T_bayes_compare <- function(x, ...) {
  df  <- data.frame(delta = x$delta)
  ci  <- x$credible_interval
  ttl <- sprintf(
    "Posterior of E'_A - E'_B\nP(E'_A > E'_B) = %.3f | %.0f%% CI: [%.2f, %.2f]",
    x$P_A_greater, x$credible_mass * 100, ci["lower"], ci["upper"]
  )
  ggplot2::ggplot(df, ggplot2::aes(x = delta)) +
    ggplot2::geom_histogram(
      ggplot2::aes(y = ggplot2::after_stat(density)),
      bins = 40, fill = "#72b7b2", alpha = 0.6
    ) +
    ggplot2::geom_density(color = "#1f2d3d", linewidth = 1) +
    ggplot2::geom_vline(xintercept = 0, linetype = "solid",
                        color = "#c0392b", linewidth = 0.8) +
    ggplot2::geom_vline(xintercept = ci["lower"], linetype = "dashed",
                        color = "#7f8c8d") +
    ggplot2::geom_vline(xintercept = ci["upper"], linetype = "dashed",
                        color = "#7f8c8d") +
    ggplot2::labs(
      x     = "Delta (E'_A - E'_B)",
      y     = "Density",
      title = ttl
    ) +
    ggplot2::theme_minimal(base_size = 12)
}
